categories = {
    "Animals": {
        "words": [
            "lion", "tiger", "elephant", "giraffe", "dolphin",
            "kangaroo", "zebra", "cheetah", "penguin", "rhinoceros",
            "hippopotamus", "alligator", "crocodile", "flamingo", "gorilla"
        ],
        "hints": [
            "King of Jungle", "Striped big cat", "Largest land animal", "Tallest animal", "Intelligent marine mammal",
            "Jumps with strong legs", "Black and white striped", "Fastest land animal", "Bird that can't fly",
            "Has a horn on its nose", "Big semi-aquatic mammal", "Large reptile with powerful jaws", 
            "Dangerous reptile with strong tail", "Pink long-legged bird", "Strong primate, lives in forests"
        ]
    },
    "Fruits": {
        "words": [
            "apple", "banana", "mango", "grape", "orange",
            "strawberry", "pineapple", "watermelon", "blueberry", "papaya",
            "kiwi", "pomegranate", "guava", "peach", "cherry"
        ],
        "hints": [
            "Keeps doctor away", "Yellow and long", "King of fruits", "Small and sweet", "Citrus fruit",
            "Red and sweet with seeds outside", "Spiky tropical fruit", "Green outside, red inside", "Small blue fruit", 
            "Tropical orange fruit with black seeds", "Brown fuzzy fruit", "Red fruit with many seeds inside", 
            "Green or pink tropical fruit", "Fuzzy orange fruit", "Small red fruit, often on desserts"
        ]
    },
    "Programming": {
        "words": [
            "python", "java", "variable", "loop", "function",
            "compiler", "algorithm", "array", "object", "inheritance",
            "recursion", "pointer", "string", "boolean", "dictionary"
        ],
        "hints": [
            "Snake or language", "Coffee language", "Stores data", "Repeating code", "Reusable code block",
            "Converts code to machine code", "Step by step solution", "Collection of elements", "Instance of class",
            "OOP concept, child gets parent properties", "Function calling itself", "Memory address reference",
            "Sequence of characters", "True or False", "Key-value storage"
        ]
    }
}



word_list = [
    'apple',
    'ball',
    'cat',
    'cat',
    'dog',
    'sun',
    'moon',
    'star',
    'book',
    'pen',
    'cup',
    'ball',
    'tree',
    'fish',
    'bird',
    'home',
    'door',
    'road',
    'car',
    'bag',
    'chair',
    'table',
    'water',
    'apple',
    'banana',
    'grape',
    'mango',
    'bread',
    'milk',
    'sugar',
    'salt',
    'plate',
    'spoon',
    'clock',
    'phone',
    'shoes',
    'socks',
    'shirt',
    'pants',
    'hat',
    'brush',
    'soap',
    'towel',
]
"""
'abruptly',
'absurd',
'abyss',
'affix',
'askew',
'avenue',
'awkward',
'axiom',
'azure',
'bagpipes',
'bandwagon',
'banjo',
'bayou',
'beekeeper',
'bikini',
'blitz',
'blizzard',
'boggle',
'bookworm',
'boxcar',
'boxful',
'buckaroo',
'buffalo',
'buffoon',
'buxom',
'buzzard',
'buzzing',
'buzzwords',
'caliph',
'cobweb',
'cockiness',
'croquet',
'crypt',
'curacao',
'cycle',
'daiquiri',
'dirndl',
'disavow',
'dizzying',
'duplex',
'dwarves',
'embezzle',
'equip',
'espionage',
'euouae',
'exodus',
'faking',
'fishhook',
'fixable',
'fjord',
'flapjack',
'flopping',
'fluffiness',
'flyby',
'foxglove',
'frazzled',
'frizzled',
'fuchsia',
'funny',
'gabby',
'galaxy',
'galvanize',
'gazebo',
'giaour',
'gizmo',
'glowworm',
'glyph',
'gnarly',
'gnostic',
'gossip',
'grogginess',
'haiku',
'haphazard',
'hyphen',
'iatrogenic',
'icebox',
'injury',
'ivory',
'ivy',
'jackpot',
'jaundice',
'jawbreaker',
'jaywalk',
'jazziest',
'jazzy',
'jelly',
'jigsaw',
'jinx',
'jiujitsu',
'jockey',
'jogging',
'joking',
'jovial',
'joyful',
'juicy',
'jukebox',
'jumbo',
'kayak',
'kazoo',
'keyhole',
'khaki',
'kilobyte',
'kiosk',
'kitsch',
'kiwifruit',
'klutz',
'knapsack',
'larynx',
'lengths',
'lucky',
'luxury',
'lymph',
'marquis',
'matrix',
'megahertz',
'microwave',
'mnemonic',
'mystify',
'naphtha',
'nightclub',
'nowadays',
'numbskull',
'nymph',
'onyx',
'ovary',
'oxidize',
'oxygen',
'pajama',
'peekaboo',
'phlegm',
'pixel',
'pizazz',
'pneumonia',
'polka',
'pshaw',
'psyche',
'puppy',
'puzzling',
'quartz',
'queue',
'quips',
'quixotic',
'quiz',
'quizzes',
'quorum',
'razzmatazz',
'rhubarb',
'rhythm',
'rickshaw',
'schnapps',
'scratch',
'shiv',
'snazzy',
'sphinx',
'spritz',
'squawk',
'staff',
'strength',
'strengths',
'stretch',
'stronghold',
'stymied',
'subway',
'swivel',
'syndrome',
'thriftless',
'thumbscrew',
'topaz',
'transcript',
'transgress',
'transplant',
'triphthong',
'twelfth',
'twelfths',
'unknown',
'unworthy',
'unzip',
'uptown',
'vaporize',
'vixen',
'vodka',
'voodoo',
'vortex',
'voyeurism',
'walkway',
'waltz',
'wave',
'wavy',
'waxy',
'wellspring',
'wheezy',
'whiskey',
'whizzing',
'whomever',
'wimpy',
'witchcraft',
'wizard',
'woozy',
'wristwatch',
'wyvern',
'xylophone',
'yachtsman',
'yippee',
'yoked',
'youthful',
'yummy',
'zephyr',
'zigzag',
'zigzagging',
'zilch',
'zipper',
'zodiac',
'zombie',
]
"""